ideas = Idea.create([
  {
	title: 		 	  Faker::Lorem.sentence(word_count: 3),
	description: 	  Faker::Lorem.sentence,
	fund_capital: 	  Faker::Commerce.price,
	industries: 	  Faker::IndustrySegments.industry,
	problem_solved:   Faker::Lorem.sentence,
	geographic_focus: 'Europe',
	team_members: 	  '1 CEO' ,
	next_steps: 	  Faker::Lorem.sentence,
	investor_require: Faker::Lorem.sentence,
  },
{
	title: 		 	  Faker::Lorem.sentence(word_count: 3),
	description: 	  Faker::Lorem.sentence,
	fund_capital: 	  Faker::Commerce.price,
	industries: 	  Faker::IndustrySegments.industry,
	problem_solved:   Faker::Lorem.sentence,
	geographic_focus: 'Asia',
	team_members: 	  '3 CEO' ,
	next_steps: 	  Faker::Lorem.sentence,
	investor_require: Faker::Lorem.sentence,
  },
  {
	title: 		 	  Faker::Lorem.sentence(word_count: 3),
	description: 	  Faker::Lorem.sentence,
	fund_capital: 	  Faker::Commerce.price,
	industries: 	  Faker::IndustrySegments.industry,
	problem_solved:   Faker::Lorem.sentence,
	geographic_focus: 'Europe',
	team_members: 	  '1 CEO, 2 CTO' ,
	next_steps: 	  Faker::Lorem.sentence,
	investor_require: Faker::Lorem.sentence,
  }
])
